import { Header } from '@/components/layout'
import { ToastProvider } from '@/components/ui'
import { Provider } from '@/components/ui/Provider'

import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <ToastProvider>
            <Header />
            <main className="mt-16 h-[calc(100vh-4rem)]">{children}</main>
          </ToastProvider>
        </Provider>
      </body>
    </html>
  )
}
